FROM mcr.microsoft.com/mssql/server:2017-latest

RUN apt-get update
RUN apt-get install unzip -y

ENV TZ=America/Sao_Paulo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN date